services:
  frontend:
    build: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:6969
  backend:
    build: backend
    ports:
      - "6969:6969"
